version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: react-build
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    command: npm start
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    depends_on:
      - frontend
